# Generated by Django 5.0.7 on 2024-08-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="contact",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("dokter", "Dokter"),
                    ("pasien", "Pasien"),
                ],
                max_length=10,
            ),
        ),
    ]
